### ISSUE TITLE
Google Cal: parse for e-conomic number

### ISSUE THREAD

**Issue by pgn** [pawel-lewtak/economic-py#10] opened 2015-01-09 08:38 UTC
Try to parse Google Calendar event description for economic number and use while registering time.

Example Description

Panowie,

Spotkajmy się na dalsze zagajenie tematu.

E-conomic: 252

Do zobaczenia,
Marek

**Comment by pawel-lewtak** [comment] 2015-01-09 08:42
It's already planned improvement but wasn't added as a task till now.

**Comment by pawel-lewtak** [comment] 2015-01-19 15:54
Closing as a duplicate of issue #3 - development will continue there.

**Closed by pawel-lewtak** 2015-01-19 15:54 UTC
Labels: duplicate
